name: bqopd
description: "The bqopd fanzine platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  intl: ^0.19.0
  firebase_storage: ^12.3.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_lints: ^5.0.0
  file_picker: ^10.0.0
  nanoid2: ^2.0.0
  go_router: ^14.2.0
  firebase_analytics: ^11.6.0

  # ADDED: Required for Rescan/Delete buttons
  cloud_functions: ^5.1.0

  # NEW: For Address Autocomplete
  flutter_google_places_sdk: ^0.3.3

  # NEW: For Social Links
  url_launcher: ^6.3.0

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  image_path_android: "assets/logo400.gif"
  ios: true
  image_path_ios: "assets/logo400.gif"

flutter:
  uses-material-design: true
  assets:
    - assets/logo200.gif
    - assets/logo400.gif
    - assets/config.json